### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by chenchen370** [saulotarsobc/electronjs-with-nextjs#7]
Some problems on  build and pack project,a blank on desk table app

**Comment by saulotarsobc** [comment]
Hello. Can you run the project successfully?

**Comment by saulotarsobc** [comment]
I'm adding mantine ui. I'll commit with Mantine soon

**Comment by saulotarsobc** [comment]
![image](https://github.com/user-attachments/assets/f8dd706e-2ef3-4f83-af73-7e0b2481980a)

https://github.com/saulotarsobc/electronjs-with-nextjs/commit/f405a16391575432e0030aa2d2d57b86d53a19cb
